### PR TITLE
A few more IO changes + Bug Fixes + Some UI goodness

### PR DESCRIPTION
**Pull request by projectgoav**
Fixed Issue #26 making JUnit tests fail within JUnit tests
Removed old RREF load and save functions - users can just recalculate once loaded (for now)
Added a deleteFile method to remove a Matrix from disk when removed from UI
Updated UI code to work with delete method
Updated JUnit test with TearDown method to remove unwanted test files once complete

### CODE REVIEW

**Comment by projectgoav** [comment]
Extras (as of b2401d6)

When Users wants to delete message, it is checked if there is a save and prompt given. Delete happens depending on outcome.
The Example & Identity2 matrix views now hide the Edit, Delete & Save buttons as they are 'constants' in my eyes. Any other matrix shows these buttons.

**Comment by Sheepzez** [comment]
Hmm. The "Example" and "Identity2" matrices are purely for test purposes, in any actual build of the application those test values would be removed. So I would say that removing the Edit, Delete and Save buttons for those matrices isn't a good idea. Especially since if any other matrix is given those names then the buttons also won't show for them.

**Comment by projectgoav** [comment]
Oh! I'm sorry about that. I thought (at least the Identity one) was like a special constant value or something that's used in calculations. I'll keep the utility function incase we need it, but I'll remove those checks.

**Comment by Sheepzez** [comment]
There is an identity matrix used in certain calculations, but its variable,
and there's an infinite amount of them xD so they can just be treated like
other matrices.

**Pull request merged**
