### PR TITLE
Save & Load Functions

### PR DESCRIPTION
**Pull request by projectgoav**
Removes most warnings from code, adds few properties of matrices and class changes.

Thought it would be better to move the operation on matrices to different classes. I did have the static, but I've changed it so you just have 2 global classes and pass in the matrices as parameters as you require. Added some tests and moved them into seperate test files as required. (A full changelog: https://gist.github.com/projectgoav/a1238d21651fa0673029)

I know it's not really the features you wanted, but thought this might be useful structurally before doing any more features. I'm kinda stumped with GUI but I'll have a look on docs about it later.

### CODE REVIEW

**Comment by Sheepzez** [comment]
Whats the purpose of getCol(int col)? Since this returns a new object any changes to it would not affect the original data.

I think I'd prefer the structure if we combined SimpleMatrixArithmetic with SolveMatrix into a single "MatrixOperations" class of some sort.

What does a SimpleMatrixArithmetic object, and a MatrixSolver object do? I'm now thinking about whether it's a good idea to break off the methods that act upon Matrices into a method separate from Matrix, since you'd have to create an SMA object everywhere you want to just do an operation on an existing matrix. What're your thoughts on this?

There's a typo in testMartixRolCol2() method declaration inside MatrixTest, but otherwise the new tests look good. But may need to be changed slightly if we decide to change any of the above.

**Comment by projectgoav** [comment]
getCol only returns a new object because there is no way to access the double array like you can with rows?

I thought they would be better in seperate classes as it'd be easier to maintain with the operations outside the main Matrix class. Perhaps just now they would be better combined, but if we get hundreds of operations it could be better in new classes.

They are just objects that allow access to the methods in those classes. I'll change them to static so instead of objects you call with SimpleMatrixArithmetic.[Method] or SolveMatrix.[Method]

I'll reflect these changes after doing some work on save/load of matrix files.

**Comment by Sheepzez** [comment]
I know there's no way around making a new object in that method, but it seems to make the method somewhat useless since there isn't really a situation that you'd need to inspect just a single column, without making any changes to it. I may be missing something though.

I know you made those changes with the idea of keeping class sizes smaller, but they're already pretty small. I agree though that if down the line, the Matrix class gets too large (>1000 or 1500 lines) then we'll need to consider some alternative, but I'm not sure what the best structure would be.

Static methods for those is definitely good, unless we go back to having them inside Matrix.

**Comment by projectgoav** [comment]
As of "Revision 5" matrices can new be saved to file. It's just a simple text file with extension ".matrix" with the format shown in comments of .save() method.

Initially the file is stored in the application root, which for Java seems to different for C# applications as it goes to the source root, not application root. This could be easily fixed with some GUI file picker and passing in a parameter filename.

There are issues in the code as in my fork I have moved the operations to a separate class (MatrixOperations). For this pull request, shall I revert those changes and copy functions back to Matrix class to break conflicts, then remove for later PRs?
8739a4afa1 1

**Comment by Sheepzez** [comment]
I would suggest deferring the structural changes (new classes/moving code)
to a later PR when we could both sit down and plan out a structure for the
future.

**Comment by projectgoav** [comment]
Both code bases are now compatible and can merge automatically.

**Comment by Sheepzez** [comment]
Everything looks good, one question though. Why did you remove the StepOne/Two/Three Unit Tests?

**Comment by projectgoav** [comment]
Oh, when I merged with your commit I lost lots of things and had to manually add them back into files myself. Merging should keep my version and your version making it complete right?

**Comment by Sheepzez** [comment]
When I merge it completely changes over to your version. What I'm going to do is merge this fork, then copy back in those tests and commit it back to master. That's not an ideal method, but it'll work for this.

**Pull request merged**
